version: "3.2"

volumes:
    bigid-mq-data:
      external: true
    bigid-scanner-data:
      external: true

services:
  bigid-ui:
    image: 742572016373.dkr.ecr.us-east-1.amazonaws.com/bigid-ui:${BIGID_VERSION}
    ports:
      - "443:443"
    links:
      - bigid-web
    environment:
     - TZ
    container_name: bigid-ui
    restart: always

  bigid-web:
    image: 742572016373.dkr.ecr.us-east-1.amazonaws.com/bigid-web:${BIGID_VERSION}
    expose:
      - "3000"
    links:
     - bigid-orch
    container_name: bigid-web
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - DEFAULT_BIGID_USER
      - DEFAULT_BIGID_PW            
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - SECRET_KEY
      - TOKEN_EXPIRATION_IN_MINUTES
      - UI_IDLE_TIMEOUT_IN_MINUTES
      - RESIDENCY_STATES_FIRST
      - MONGO_EXTERNAL_FULL_URL
      - SHOW_MOCK_APPLICATIONS
      - PII_SUMMARY_SCALE_ENABLED
      - TZ
      - BIG_ID_REPORT_LANGUAGE
      - BIGID_SAML_PRIVATE_CERT_PATH
      - HIDE_ATTRIBUTE_PURPOSE_OF_USE
      - BIGID_PRODUCT_TYPE
      - ENTITY_LEVEL_TAGGING_SUPPORTED
      - USE_EXTENDED_PERMISSIONS
      - NEW_RELIC_LICENSE_KEY
      - MONITORING_CUSTOMER_NAME
      - APPEND_TO_JSON_LOGS
      - MICROSOFT_GRAPH_API_PAGE_SIZE
      - DATA_CATALOG_ENABLED
      - METADATA_CLASSIFIER_ENABLED
    restart: always

  bigid-orch:
    image: 742572016373.dkr.ecr.us-east-1.amazonaws.com/bigid-orch:${BIGID_VERSION}
    expose:
      - "3001"
    links:
      - bigid-scanner
      - bigid-mq
    container_name: bigid-orch
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - SECRET_KEY
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - ORCHESTRATOR_URL_EXT # If the Scanner is on a different Docker host, preferably Internal IP.
      - ORCHESTRATOR_URL_PUBLIC # Public IP: For Hadoop and EMR, in case Hadoop / EMR cluster are outside the VPC. If not set, hadoop callback URL will use ORCHESTRATOR_URL_EXT.
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - SAVE_SCANNED_IDENTITIES_AS_PII_FINDINGS
      - SCANNED_VALUES_IGNORE_LIST
      - TRUST_SELF_SIGNED_CERTS
      - IS_CALC_PSEUDO_PII
      - JIT_FILTER_LOW_CONFIDENCE_FACTOR
      - SAR_ONLY_STRICT_MATCHES
      - LINEAGE_ATTRIBUTES_BY_CONFIDENCE
      - METADATA_ACL_SCAN_ENABLED
      - PII_SUMMARY_SCALE_ENABLED
      - DATA_SOURCE_ACL_SCAN_ENABLED
      - TZ
      - CONCURRENT_CORRELATION
      - CORRELATION_RECOVERY_SCHEDULER_FLAG
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG
      - IDENTITY_RESOLUTION_ENABLED
      - RUN_RETENTION_POLICY_PROCESS
      - SCAN_PARTS_ENABLED
      - NEW_RELIC_LICENSE_KEY
      - MONITORING_CUSTOMER_NAME
      - APPEND_TO_JSON_LOGS
      - METADATA_CLASSIFIER_ENABLED
    hostname: bigid-orch
    restart: always

  bigid-orch2:
    image: 742572016373.dkr.ecr.us-east-1.amazonaws.com/bigid-orch:${BIGID_VERSION}
    expose:
      - "3003"
    links:
      - bigid-scanner
      - bigid-mq
    container_name: bigid-orch2
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - SECRET_KEY
      - MONGO_EXTERNAL_FULL_URL
      - ORCHESTRATOR_URL_EXT # If the Scanner is on a different Docker host, preferably Internal IP.
      - ORCHESTRATOR_URL_PUBLIC # Public IP: For Hadoop and EMR, in case Hadoop / EMR cluster are outside the VPC. If not set, hadoop callback URL will use ORCHESTRATOR_URL_EXT.
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - SAVE_SCANNED_IDENTITIES_AS_PII_FINDINGS
      - SCANNED_VALUES_IGNORE_LIST
      - TRUST_SELF_SIGNED_CERTS
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG
      - PORT=3003
      - IS_ORCH2=true
      - CONCURRENT_CORRELATION
      - TZ
      - NEW_RELIC_LICENSE_KEY
      - MONITORING_CUSTOMER_NAME
      - APPEND_TO_JSON_LOGS
      - METADATA_CLASSIFIER_ENABLED
    hostname: bigid-orch2
    restart: always

  bigid-scanner:
    image: 742572016373.dkr.ecr.us-east-1.amazonaws.com/bigid-scanner:${BIGID_VERSION}
    expose:
      - "9999"
    container_name: bigid-scanner
    user: bigid
    hostname: bigid-scanner
    environment:
      - SCANNER_JAVA_OPTS
      - THREAD_POOL_SIZE
      - SCANNER_THREADS
      - ORCH_ASYNCH
      - BIGID_USER
      - IGNORE_MEDIA_TYPE # list of Tika MediaType that overwrite as MediaType.TEXT_PLAIN
      - BIGID_PASSWORD
      - SCANNER_HOST_NAME
      - SCANNER_GROUP_NAME
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - HADOOP_DIST
      - TZ
      - ENABLE_GENERIC_REST_API_CONNECTOR=${ENABLE_GENERIC_REST_API_CONNECTOR:-false}
      - S3_USE_CUSTOM_REGION=${S3_USE_CUSTOM_REGION:-false}
      - S3_AWS_REGION
      - NEW_RELIC_LICENSE_KEY
      - MONITORING_CUSTOMER_NAME
      - APPEND_TO_JSON_LOGS
    privileged: true
    volumes:
      - bigid-scanner-data:/etc/scanner
    restart: always

  bigid-mq:
      image: rabbitmq:3.6.16-management
      ports:
        - "15671:15671"
        - "5671:5671"
      container_name: bigid-mq
      hostname: rabbitmq
      volumes:
        - bigid-mq-data:/etc/rabbitmq
        - bigid-mq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      restart: on-failure:5
      environment:
        - TZ
        - NEW_RELIC_LICENSE_KEY
        - MONITORING_CUSTOMER_NAME
        - APPEND_TO_JSON_LOGS

  bigid-corr-new:
    image: 742572016373.dkr.ecr.us-east-1.amazonaws.com/bigid-corr-new:${BIGID_VERSION}
    expose:
      - "7082"
    container_name: bigid-corr-new
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_IGNITE_HOST_EXT
      - NEW_CORR_JVM_OPTS=${NEW_CORR_JVM_OPTS:--server -Xmx10g -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC}
      - NEW_CORR_JVM_SSL_OPTS
      - SPRING_PROFILES_ACTIVE
      - GENERATE_IDENTITIES_ON_START_UP
      - NEW_RELIC_LICENSE_KEY
      - MONITORING_CUSTOMER_NAME
      - APPEND_TO_JSON_LOGS
      - NUMBERS_LENGTH_THRESHOLD
    restart: always
#    ports:
#      - 7082:7082 # new corr restful API
#      - 10800:10800 # ignite SQL port number.
#      - 49112:49112 # JMX port number.
#      - 11211:11211
#      - 47100:47100 # communication SPI port number.
#      - 47400:47400
#      - "47500-47509:47500-47509" # discovery SPI port number.
